SELECT USER
FROM DUAL;
--==>> SCOTT


--○ 테이블 생성(TBL_STUDENT)
CREATE TABLE TBL_STUDENT
( SID       NUMBER
, NAME      VARCHAR2(30)
, TEL       VARCHAR2(40)
, CONSTRAINT SID_PK PRIMARY KEY(SID)
);
--==>> Table TBL_STUDENT이(가) 생성되었습니다.


--○ 시퀀스 생성(STUDENTSEQ)
CREATE SEQUENCE STUDENTSEQ
NOCACHE;
--==>> Sequence STUDENTSEQ이(가) 생성되었습니다.


--○ 샘플 데이터 입력(TBL_STDUENT)
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(STUDENTSEQ.NEXTVAL, '장서현', '010-1111-1111');
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(STUDENTSEQ.NEXTVAL, 'NCT127', '010-4444-4444');



--○ 테이블 생성(TBL_GRADE)
CREATE TABLE TBL_GRADE
( SID       NUMBER
, SUB1      NUMBER(3)
, SUB2      NUMBER(3)
, SUB3      NUMBER(3)
, CONSTRAINT GRD_SID_PK PRIMARY KEY(SID)
, CONSTRAINT GRD_SID_FK FOREIGN KEY(SID) REFERENCES TBL_STUDENT(SID)
, CONSTRAINT GRD_SUB1_CK CHECK(SUB1 BETWEEN 0 AND 100)
, CONSTRAINT GRD_SUB2_CK CHECK(SUB2 BETWEEN 0 AND 100)
, CONSTRAINT GRD_SUB3_CK CHECK(SUB3 BETWEEN 0 AND 100)
);
--==>> Table TBL_GRADE이(가) 생성되었습니다.


--○ 샘플 데이터 입력(TBL_GRADE)
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(1, 90, 80, 70);
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(2, 70, 60, 50);
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(3, 50, 40, 30);
INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(4, 90, 90, 30);


--○ 커밋
COMMIT;


--○ 뷰 생성(STUDENTVIEW)
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT SID, NAME, TEL,
    (SELECT COUNT(*)
    FROM TBL_GRADE
    WHERE SID = S.SID) AS SUB
FROM TBL_STUDENT S;
--==>> View STUDENTVIEW이(가) 생성되었습니다.


--○ 뷰 조회(STUDENTVIEW)
SELECT SID, NAME, TEL, SUB
FROM STUDENTVIEW
ORDER BY SID;
/*
1	장서현	010-1111-1111	1
2	아이유	010-2222-2222	1
3	박효신	010-3333-3333	1
4	NCT127	010-4444-4444	1
*/


--○ 뷰 생성(GRADEVIEW)
CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT S.SID AS SID, S.NAME AS NAME, G.SUB1 AS SUB1, G.SUB2 AS SUB2, G.SUB3 AS SUB3
, (G.SUB1+G.SUB2+G.SUB3) AS TOT
, ((G.SUB1+G.SUB2+G.SUB3)/3) AS AVG
, CASE
    WHEN ((G.SUB1+G.SUB2+G.SUB3)/3)<60 THEN '불합격'
    WHEN G.SUB1<40 OR G.SUB2<40 OR G.SUB3<40 THEN '과락'
    ELSE '합격'
    END AS CH
FROM TBL_STUDENT S LEFT JOIN TBL_GRADE G
ON S.SID=G.SID;
--==>> View GRADEVIEW이(가) 생성되었습니다.


--○ 뷰 조회(GRADEVIEW)
SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW
ORDER BY 1;
/*
1	장서현	90	80	70	240	80	합격
2	아이유	70	60	50	180	60	합격
3	박효신	50	40	30	120	40	불합격
4	NCT127	90	90	30	210	70	과락
*/